### ISSUE TITLE
Vertical slider is not shown in storybook

### ISSUE THREAD

**Issue by Artur-A** [airbnb/rheostat#54]
Hi,

In the process of porting this awesome project to [typescript](https://github.com/Artur-A/ts-rheostat) I've faced an issue with default vertical style, which has no visual height:

![problem](https://media.giphy.com/media/l3vReNSEWLJUQA8co/giphy.gif)

There are many solutions, for example `min-height` and `position: absolute` can solve it:
```less
.rheostat-vertical {
    ...
    min-height: 200px;

    .rheostat-background {
        ....
        position: absolute;
    }
```
